### ISSUE TITLE
Stack SVGs on top of one another

### ISSUE THREAD

**Issue by achimmihca** [astraw/svg_stack#11]
The tool can put SVG next to each other. I am looking for something that puts SVGs on top of one another. Would it be possible to do this with this tool or do you know another tool that can do it?

**Comment by achimmihca** [comment]
I think this can do is what I want: https://github.com/Amirh24/SVG-Image-Utils
This Ticket can be closed.
Thx

**Comment by matkoniecz** [comment]
> This Ticket can be closed.

You can do that as an issue reporter.
