### ISSUE TITLE
A thank you

### ISSUE THREAD

**Issue by xihajun** [astraw/svg_stack#23]
Thanks for svg_stack! It is the one I am looking for for so long. 

Although javascript can do the job as well, I am really happy to find a python solution!

Many thanks,
Jun

**Comment by astraw** [comment]
You are welcome! Thanks for the feedback.

**Comment by xihajun** [comment]
Thanks, I have some thought while using this tool. So I wonder if it is doable to change the different size svg files into the same size and then do the merge automatically?

**Comment by astraw** [comment]
It might be possible but I cannot spend time to work on it.
