### ISSUE TITLE
Does not work with python 3

### ISSUE THREAD

**Issue by ste101** [astraw/svg_stack#3]
Please add a comment that svg_stack does not work with python 3

**Comment by dhimmel** [comment]
An open pull request by @varnion adds Python 3 compatibility. Bummer that `astraw/svg_stack`  doesn't seem to be actively maintained.

I'd recommend installing the fork like:

```
pip install git+https://github.com/varnion/svg_stack@d324a93a42d80c98a2ed27e4004a1781b44ffc0a
```

**Comment by branditodesign** [comment]
Using the instructions provided by @dhimmel worked for me running the following stack:
Python 2.7.16
pip 18.1 from /usr/lib/python2.7/dist-packages/pip (python 2.7)

Previously this was not working at all as intended, although with the changes from above it works perfectly.

SVG Stack works exactly how I want it to work for what I am working on at the moment, this is a HUGE time saver as it has allowed me to automate the most time consuming parts of my current project.

**Comment by astraw** [comment]
Fixed recently on the main branch. Sorry for the delay! Glad it is useful.
