### ISSUE TITLE
Make installation requirements explicit in setup.py

### ISSUE THREAD

**Issue by metasoarous** [astraw/svg_stack#5]
I just "successfully installed" svg_stack, only to find that the `svg_stack.py` script would not run without first installing `lxml` (which was easy to do with `pip install lxml`). It would be nice if installation failed without this dependency, for the sake of clarity.

**Comment by astraw** [comment]
Fixed in ac0459d5d07a83e4a07ae3c6bbe97cdacd7fc055. Thanks for the report and sorry for the long delay.
